[package]
name = "cw3-fixed-multisig"
version = "0.6.2"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementing cw3 with an fixed group multisig"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw0 = { path = "../../packages/cw0", version = "0.6.2" }
cw2 = { path = "../../packages/cw2", version = "0.6.2" }
cw3 = { path = "../../packages/cw3", version = "0.6.2" }
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.6.2", features = ["iterator"] }
cosmwasm-std = { version = "0.15.0", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }

[dev-dependencies]
cosmwasm-schema = { version = "0.15.0" }
cw20 = { path = "../../packages/cw20", version = "0.6.2" }
cw20-base = { path = "../cw20-base", version = "0.6.2", features = ["library"] }
cw-multi-test = { path = "../../packages/multi-test", version = "0.6.2" }
