[package]
name = "cw-multi-test"
version = "0.6.0-beta1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["iterator"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]

[dependencies]
cw0 = { path = "../../packages/cw0", version = "0.6.0-beta1" }
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.6.0-beta1" }
cosmwasm-std = { version = "0.14.0-beta3" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
