[package]
name = "cw1-whitelist"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementation of an proxy contract using a whitelist"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
#cw1 = { path = "../../packages/cw1", version = "0.1.0" }
cosmwasm-std = { version = "0.9.2", features = ["iterator"] }
cosmwasm-storage = { version = "0.9.2", features = ["iterator"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

[dev-dependencies]
cosmwasm-schema = { version = "0.9.2" }
