[package]
name = "cw1-whitelist"
version = "0.6.0-alpha3"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implementation of an proxy contract using a whitelist"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cw0 = { path = "../../packages/cw0", version = "0.6.0-alpha3" }
cw1 = { path = "../../packages/cw1", version = "0.6.0-alpha3" }
cw2 = { path = "../../packages/cw2", version = "0.6.0-alpha3" }
cosmwasm-std = { version = "0.14.0-beta3", features = ["iterator"] }
cw-storage-plus = { path = "../../packages/storage-plus", version = "0.6.0-alpha3", features = ["iterator"] }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }

[dev-dependencies]
cosmwasm-schema = { version = "0.14.0-beta3" }
