[package]
name = "cw1-subkeys"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implement subkeys for authorizing native tokens as a cw1 proxy contract"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "0.10.0-alpha2", features = ["iterator"] }
cosmwasm-storage = { version = "0.10.0-alpha2", features = ["iterator"] }
cw20 = { path = "../../packages/cw20", version = "0.1.0" }
cw1-whitelist = { path = "../cw1-whitelist", version = "0.1.0" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

[dev-dependencies]
cosmwasm-schema = { version = "0.10.0-alpha2" }
