[package]
name = "cw1-subkeys"
version = "0.1.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Implement subkeys for authorizing native tokens as a cw1 proxy contract"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cosmwasm-std = { version = "0.10.0", features = ["iterator"] }
cosmwasm-storage = { version = "0.10.0", features = ["iterator"] }
cw0 = { path = "../../packages/cw0", version = "0.1.1" }
cw1 = { path = "../../packages/cw1", version = "0.1.1" }
cw2 = { path = "../../packages/cw2", version = "0.1.1" }
cw1-whitelist = { path = "../cw1-whitelist", version = "0.1.1", features = ["library"] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
snafu = { version = "0.6.3" }

[dev-dependencies]
cosmwasm-schema = { version = "0.10.0" }
